/** @format */
export const categories = [
  { id: 885, name: "test category" },
  { id: 88885, name: " category" },
  { id: 89985, name: "test " },
  { id: 88255, name: "sub categoroy " },
  { id: 88245, name: "test " },
];
export const group = [
  { id: 885, name: "test group" },
  { id: 88885, name: " group" },
  { id: 89985, name: "test " },
  { id: 88255, name: "sub group " },
  { id: 88245, name: "test " },
];
export const sub = [
  { id: 885, name: "test sub" },
  { id: 88885, name: " sub" },
  { id: 89985, name: "sub " },
  { id: 88255, name: "sub categoroy " },
  { id: 88245, name: "test sub " },
];
export const Customers = [
  {
    id: 1,
    name: "Ahmed ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 2,
    name: "Mohamed",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 3,
    name: "Ali",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 4,
    name: "Ail ",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 5,
    name: "Ail ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 6,
    name: "Ail",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 8,
    name: "Ail",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 9,
    name: "Ail ",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },

  {
    id: 10,
    name: "Ahmed ",
    type: "Lorem Surgery",
    mostOrder: "Plates and Secrews ",
    orderValue: "119$",
    ratingRate: "4/5",
  },
  {
    id: 11,
    name: "Mohamed ",
    type: "Ipsum Surgery",
    mostOrder: "Nail System ",
    orderValue: "230$",
    ratingRate: "4/5",
  },

  {
    id: 12,
    name: "Ali ",
    type: "Dolor Surgery",
    mostOrder: "On pipe ",
    orderValue: "120$",
    ratingRate: "4/5",
  },
  {
    id: 13,
    name: "Ail",
    type: "Sit Surgery",
    mostOrder: "Bone Cement",
    orderValue: "121$",
    ratingRate: "4/5",
  },
];
export const Products = [
  {
    id: 1,
    listName: "product",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 771,
    listName: "product test",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "229$",
  },
  {
    id: 881,
    listName: "test",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 881,
    listName: "product",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "119$",
  },
  {
    id: 631,
    listName: "product test",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "229$",
  },
  {
    id: 333,
    listName: "test",
    name: "S type clavical ",
    itemNumber: "1",
    type: "Lorem ",
    mostOrder: "Plates and Secrews ",
    subgroup: "sub collection",
    orderValue: "Trauma",
    price: "119$",
  },
];
export const Stuff = [
  {
    id: 1,
    name: "Ahmed ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1996/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
  {
    id: 28,
    name: "Ail ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1996/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
  {
    id: 2,
    name: "maher ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1999/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
  {
    id: 661,
    name: "Ahmed ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1996/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
  {
    id: 62,
    name: "Ail ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1996/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
  {
    id: 52,
    name: "maher ",
    type: "Lorem",
    mostOrder: "Plates and Secrews ",
    phone: "07756412365",
    orderValue: "119",
    location: "Iraq",
    birthday: "1999/5/6",
    email: "Lorem@gmail.com",
    ratingRate: "4/5",
  },
];
